#!/bin/bash

# AGROMETA Installation Script
# Run this after git clone to set up the project

set -e  # Exit on error

echo "🌱 AGROMETA Installation Starting..."
echo "======================================"

# Prerequisites check
echo "📦 Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first:"
    echo "   https://docs.docker.com/engine/install/"
    exit 1
fi

if ! command -v docker compose &> /dev/null; then
    echo "❌ Docker Compose is not installed. Please install Docker Compose:"
    echo "   https://docs.docker.com/compose/install/"
    exit 1
fi

echo "✅ Docker and Docker Compose are installed"

# Ensure bcrypt is in package.json
echo ""
echo "📝 Checking backend dependencies..."
if ! grep -q '"bcrypt"' backend/package.json; then
    echo "⚠️  Adding bcrypt to package.json..."
    # Add bcrypt to dependencies
    sed -i '/"dependencies": {/a \    "bcrypt": "^5.1.1",' backend/package.json
    echo "✅ bcrypt added"
else
    echo "✅ bcrypt already present"
fi

# ============================================
# 🔐 Generate JWT_SECRET if not exists
# ============================================

echo ""
echo "🔐 Setting up environment variables..."

if [ ! -f "backend/.env" ]; then
    echo "📝 Creating backend/.env file..."
    
    # Generate strong JWT_SECRET
    if command -v node &> /dev/null; then
        JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")
    elif command -v openssl &> /dev/null; then
        JWT_SECRET=$(openssl rand -hex 64)
    else
        echo "❌ Error: Neither node nor openssl available to generate JWT_SECRET"
        exit 1
    fi
    
    # Create .env with JWT_SECRET
    cat > backend/.env << EOF
# Auto-generated by install.sh on $(date)

# Security
JWT_SECRET=$JWT_SECRET
NODE_ENV=production

# Database (Docker internal)
DATABASE_URL="postgresql://sera_user:sera_password@postgres:5432/sera_db?schema=public"

# Server
PORT=3009

# SMTP (optional - configure later)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=

# SMS (optional - configure later)
SMS_API_KEY=
SMS_API_URL=
EOF

    echo "✅ backend/.env created with JWT_SECRET"
    echo "   JWT_SECRET length: ${#JWT_SECRET} characters"
else
    echo "✅ backend/.env already exists"
    
    # Check if JWT_SECRET exists in .env
    if ! grep -q "^JWT_SECRET=" backend/.env; then
        echo "⚠️  JWT_SECRET not found in .env, adding it..."
        
        if command -v node &> /dev/null; then
            JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")
        else
            JWT_SECRET=$(openssl rand -hex 64)
        fi
        
        echo "" >> backend/.env
        echo "# Added by install.sh on $(date)" >> backend/.env
        echo "JWT_SECRET=$JWT_SECRET" >> backend/.env
        echo "✅ JWT_SECRET added to existing .env"
    else
        echo "✅ JWT_SECRET already configured"
    fi
fi

# ============================================
# 🔐 Create root .env for docker-compose
# ============================================

echo ""
echo "🔐 Creating root .env for Docker Compose..."

# Extract JWT_SECRET from backend/.env
if [ -f "backend/.env" ]; then
    JWT_SECRET=$(grep "^JWT_SECRET=" backend/.env | cut -d'=' -f2)
    
    if [ -z "$JWT_SECRET" ]; then
        echo "❌ Error: JWT_SECRET not found in backend/.env"
        exit 1
    fi
    
    # Create root .env for docker-compose
    cat > .env << EOF
# Docker Compose Environment Variables
# Auto-generated by install.sh

# Security - Required for docker-compose.yml
JWT_SECRET=$JWT_SECRET

# Database
POSTGRES_USER=sera_user
POSTGRES_PASSWORD=sera_password
POSTGRES_DB=sera_db

# Node Environment
NODE_ENV=production
EOF
    
    echo "✅ Root .env created for Docker Compose"
else
    echo "❌ Error: backend/.env not found"
    exit 1
fi

# Stop any running containers
echo ""
echo "🛑 Stopping existing containers..."
docker compose down || true

# Build containers
echo ""
echo "🏗️  Building Docker containers (this may take a few minutes)..."
docker compose build --no-cache

# Start services
echo ""
echo "🚀 Starting services..."
docker compose up -d

# Wait for database to be ready
echo ""
echo "⏳ Waiting for database to be ready..."
sleep 10

# Run migrations
echo ""
echo "🔄 Running database migrations..."
docker compose exec -T backend npx prisma migrate deploy || {
    echo "⚠️  Migration failed, trying to generate Prisma client..."
    docker compose exec -T backend npx prisma generate
    docker compose exec -T backend npx prisma migrate deploy
}

# Restart backend to ensure changes are loaded
echo ""
echo "♻️  Restarting backend..."
docker compose restart backend

# Wait for backend to be ready
sleep 5

# Test if backend is responding
echo ""
echo "🧪 Testing backend..."
if curl -s http://localhost:3000/ > /dev/null; then
    echo "✅ Backend is running"
else
    echo "⚠️  Backend may not be ready yet, checking logs..."
    docker compose logs backend | tail -20
fi

# Final status
echo ""
echo "======================================"
echo "🎉 Installation Complete!"
echo "======================================"
echo ""
echo "📌 Next Steps:"
echo "   1. Open your browser: http://localhost:5173"
echo "   2. You should see the Setup Wizard (first time only)"
echo "   3. Create your admin account and farm"
echo ""
echo "📊 Useful Commands:"
echo "   - View logs:    docker compose logs -f"
echo "   - Stop:         docker compose down"
echo "   - Restart:      docker compose restart"
echo "   - Rebuild:      docker compose up -d --build"
echo ""
echo "🔧 Troubleshooting:"
echo "   - If Setup page doesn't appear, run: docker compose restart"
echo "   - Check backend logs: docker logs agrometa_backend"
echo "   - Check database: docker exec -it agrometa_db psql -U postgres -d agrometa"
echo ""
